apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-storageclass-manager
  labels:
    app: jenkins
    component: rbac
rules:
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "create", "update", "patch", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-storageclass-binding
  labels:
    app: jenkins
    component: rbac
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins  # Jenkins가 실행되는 네임스페이스
roleRef:
  kind: ClusterRole
  name: jenkins-storageclass-manager
  apiGroup: rbac.authorization.k8s.io 