apiVersion: v1
kind: ServiceAccount
metadata:
  name: etf-chatbot
  namespace: etf-chatbot
  labels:
    app: etf-chatbot
    component: service-account
---
# ETF 챗봇에 필요한 최소 권한만 부여
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etf-chatbot-role
  namespace: etf-chatbot
  labels:
    app: etf-chatbot
rules:
# 기본 리소스 읽기 권한
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# 앱 관련 읽기 권한
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etf-chatbot-binding
  namespace: etf-chatbot
  labels:
    app: etf-chatbot
subjects:
- kind: ServiceAccount
  name: etf-chatbot
  namespace: etf-chatbot
roleRef:
  kind: Role
  name: etf-chatbot-role
  apiGroup: rbac.authorization.k8s.io 