# -*- coding: utf-8 -*-
"""이것저것 다.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNOBmEHImwymYcfA9LiEhHiCvPxqhTJp
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

personal = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/개인특성_근무자수_증감률.xlsx")
employ_instab = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/산업특성_고용불안정도.xlsx")
employ_instab_age = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/산업특성_고용불안정도_연령.xlsx")


accident_num = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/산업특성_산업재해현황.xlsx")
employ_num = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/2023_근무자수.xlsx")

personal = personal.fillna(method='ffill')
personal.rename(columns={'증감률' : '근무자수_증감률'}, inplace=True)

# personal['연령'] 열 값 수정
personal['연령'] = personal['연령'].replace({
    "50 ~ 54": "50세~54세",
    "55 ~ 59": "55세~59세",
    "60세 ~": "60세 이상"
})

personal

employ_instab_age

employ_instab_age = employ_instab_age.fillna(method = 'ffill')

# '60세 이상' 연령군 필터링
age_filter = employ_instab_age['Unnamed: 2'].isin(['60~64세 이하', '65~69세 이하', '70세 이상'])
df_60up = employ_instab_age[age_filter]

# 그룹별 합산
agg_df = df_60up.groupby(['Unnamed: 0', 'Unnamed: 1'])[['2022년12월', '2023년12월']].sum().reset_index()
agg_df['Unnamed: 2'] = '60세 이상'

# 기존 데이터프레임에서 해당 연령 행 제거
employ_instab_age = employ_instab_age[~age_filter]

# 새로운 합산 행 추가
employ_instab_age = pd.concat([employ_instab_age, agg_df], ignore_index=True)

employ_instab_age = employ_instab_age[employ_instab_age['Unnamed: 2'].isin(['50~54세 이하', '55~59세 이하', '60세 이상'])].reset_index()
employ_instab_age['피보험자수_증감률'] = ((employ_instab_age['2023년12월'] - employ_instab_age['2022년12월']) / employ_instab_age['2022년12월'])*100
employ_instab_age.drop(columns=['index', '2022년12월', '2023년12월'], inplace=True)
employ_instab_age.rename(columns = {'Unnamed: 0' : '대분류', 'Unnamed: 1' : '중분류', 'Unnamed: 2' : '연령'}, inplace = True)


# personal['연령'] 열 값 수정
employ_instab_age['연령'] = employ_instab_age['연령'].replace({
    "50~54세 이하": "50세~54세",
    "55~59세 이하": "55세~59세",
})

employ_instab_age

employ_instab_age['중분류'] = employ_instab_age['중분류'].str.replace('10차_', '', regex=False)
employ_instab_age['대분류'] = employ_instab_age['대분류'].str.replace('10차_', '', regex=False)

employ_instab_age

employ_instab['피보험자수_증감률'] = ((employ_instab['2023년12월'] - employ_instab['2022년12월']) / employ_instab['2022년12월'])*100
employ_instab.drop(columns=['2022년12월', '2023년12월'], inplace=True)
employ_instab.rename(columns = {'Unnamed: 0' : '중분류'}, inplace = True)
employ_instab

import numpy as np
from sklearn.preprocessing import MinMaxScaler
personal['근무자수_증감률'] = personal['근무자수_증감률'].replace('-', np.nan).astype(float)
personal['근무자수_증감률'] = personal['근무자수_증감률'].astype(float)

scaler = MinMaxScaler()
personal['근무자수_증감률'] = scaler.fit_transform(personal[['근무자수_증감률']])
personal

"""## 최종 산업안정도 dataset join

"""

hire_stable = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/안정성_점수_가중합_최종결과.xlsx")
accident_safety = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/재해안정도.xlsx")

hire_stable['연령'] = hire_stable['연령'].replace({
    '50 ~ 54': '50세~54세',
    '55 ~ 59': '55세~59세',
    '60세 ~': '60세 이상'
})
hire_stable

merged = pd.merge(hire_stable, accident_safety, left_on=['산업_대분류', '연령'], right_on=['산업분류별', '연령'], how='inner')
merged = merged.drop(columns=['산업분류별'])
merged = merged.rename(columns={
    '학력별' : '학력',
    '최종점수': '고용안정도',
    '재해율_정규화': '재해안전성'
})

merged['최종점수(5:5)'] = merged['고용안정도'] * 0.5 + merged['재해안전성'] * 0.5
merged['최종점수(3:7)'] = merged['고용안정도'] * 0.3 + merged['재해안전성'] * 0.7
merged['최종점수(7:3)'] = merged['고용안정도'] * 0.7 + merged['재해안전성'] * 0.3

merged = merged.drop(['피보험자수_안정성점수', '근무자수_안정성점수'], axis = 1)
merged = merged.rename(columns={
    '최종점수(5:5)' : '최종_산업안정도(5:5)',
    '최종점수(3:7)': '최종_산업안정도(3:7)',
    '최종점수(7:3)': '최종_산업안정도(7:3)'
})
merged

merged.to_excel('산업안정도.xlsx', index=False)