# -*- coding: utf-8 -*-
"""재해안정도.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0m8QjC-jd_0-BOmLaipzKohzY1Ptb4m
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

accident_num = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/산업특성_산업재해현황.xlsx")
employ_num = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/KUBIG/25-1/Conference/2023_근무자수.xlsx")

accident_num['대업종'] = accident_num['대업종'].str.replace(" ", "")

agg_cols = ['50세~54세', '55세~59세', '60세 이상']
subtotals = (
    accident_num[accident_num['대업종'].isin(['광업', '제조업'])]
    .groupby('대업종')[agg_cols]
    .sum()
    .reset_index()
    .assign(중업종=['광업 소계', '제조업 소계'])  # 중업종을 '소계'로 지정
)
# 원본 데이터프레임에 소계 행 추가
accident_num = pd.concat([accident_num, subtotals], ignore_index=True)


# '임 업', '어 업', '농 업'을 선택
selected = accident_num[accident_num['대업종'].isin(['임업', '어업', '농업'])]
sum_row = selected[['50세~54세', '55세~59세', '60세 이상']].sum()
sum_row['대업종'] = 'A.농업, 임업 및 어업(01~03)'
sum_row['중업종'] = 'A.농업, 임업 및 어업(01~03) 소계'

# 기존 데이터프레임에 추가
accident_num = pd.concat([accident_num, pd.DataFrame([sum_row])], ignore_index=True)
accident_num = accident_num.drop(accident_num.index[1:14])
accident_num

employ_num

mapping = {
    'A.농업, 임업 및 어업(01~03) 소계' : 'A.농업, 임업 및 어업(01~03)',
    '광업 소계' : 'B.광업(05~08)',
    '제조업 소계' : 'C.제조업(10~34)',
    '전기·가스·증기·수도사업' : 'D.전기, 가스, 증기 및 공기 조절 공급업(35)',
    '건설업' : 'F.건설업(41~42)',
    '통신업' : 'J.정보통신업(58~63)',
    '금융및보험업' : 'K.금융 및 보험업(64~66)',
    '부동산업및임대업' : 'L.부동산업(68)',
    '시설관리및사업지원서비스업' : 'N.사업시설 관리, 사업 지원 및 임대 서비스업(74~76)'
}

accident_num['산업분류별'] = accident_num['중업종'].map(mapping)
accident_num = accident_num[['산업분류별', '50세~54세', '55세~59세', '60세 이상']]

employ_num = employ_num.rename(columns={
    '50 ~ 54': '50세~54세',
    '55 ~ 59': '55세~59세',
    '60세 ~': '60세 이상'
})

merged = pd.merge(employ_num, accident_num, on='산업분류별', suffixes=('_근로자', '_재해자'), how='left')
merged

merged.loc[merged['산업분류별'] == 'E.수도, 하수 및 폐기물 처리, 원료 재생업(36~39)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (18,14,35)
merged.loc[merged['산업분류별'] == 'G.도매 및 소매업(45~47)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (1855,2096,3043)
merged.loc[merged['산업분류별'] == 'H.운수 및 창고업(49~52)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (1807, 1737, 2486)
merged.loc[merged['산업분류별'] == 'I.숙박 및 음식점업(55~56)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (479,713,1679)
merged.loc[merged['산업분류별'] == 'M.전문, 과학 및 기술 서비스업(70~73)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (305,271,632)
merged.loc[merged['산업분류별'] == 'P.교육 서비스업(85)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (213,266,460)
merged.loc[merged['산업분류별'] == 'Q.보건업 및 사회복지서비스업(86~87)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (690,978,2630)
merged.loc[merged['산업분류별'] == 'R 예술, 스포츠 및 여가관련 서비스업(90~91)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (39,47,104)
merged.loc[merged['산업분류별'] == 'S 협회 및 단체, 수리 및 기타 개인 서비스업(94~96)', ['50세~54세_재해자', '55세~59세_재해자', '60세 이상_재해자']] = (240, 221, 698)

# 재해율 계산
for col in ['50세~54세', '55세~59세', '60세 이상']:
    merged[col + '_재해율'] = merged[f'{col}_재해자'] / merged[f'{col}_근로자'] * 100

indust_risk = merged[['산업분류별', '50세~54세_재해율', '55세~59세_재해율', '60세 이상_재해율']]
indust_risk

# 정규화
indust_risk = indust_risk.copy()

# 1. 60세 이상 열: 로그 변환 + 정규화
indust_risk.loc[:, '60세 이상_재해율_log'] = np.log1p(indust_risk['60세 이상_재해율'])
min_val = indust_risk['60세 이상_재해율_log'].min()
max_val = indust_risk['60세 이상_재해율_log'].max()
indust_risk.loc[:, '60세 이상_재해율_정규화'] = (indust_risk['60세 이상_재해율_log'] - min_val) / (max_val - min_val)
indust_risk.drop(columns=['60세 이상_재해율_log'], inplace=True)

# 2. 나머지 열: MinMaxScaler 정규화
scaler = MinMaxScaler()
scaled = scaler.fit_transform(indust_risk[['50세~54세_재해율', '55세~59세_재해율']])
indust_risk.loc[:, ['50세~54세_재해율_정규화', '55세~59세_재해율_정규화']] = scaled

cols_to_invert = ['60세 이상_재해율_정규화', '50세~54세_재해율_정규화', '55세~59세_재해율_정규화']
for col in cols_to_invert:
  indust_risk[col] = 1 - indust_risk[col]

indust_risk = indust_risk[['산업분류별', '50세~54세_재해율_정규화', '55세~59세_재해율_정규화', '60세 이상_재해율_정규화']]
indust_risk

df = indust_risk
df_melted = pd.melt(
    df,
    id_vars=['산업분류별'],
    value_vars=[
        '50세~54세_재해율_정규화',
        '55세~59세_재해율_정규화',
        '60세 이상_재해율_정규화'
    ],
    var_name='연령',
    value_name='재해율_정규화'
)

# '연령' 컬럼에서 '~_재해율_정규화' 문자열 제거
df_melted['연령'] = df_melted['연령'].str.replace('_재해율_정규화', '', regex=False)
df_melted

df_melted.to_excel('재해안정도.xlsx', index=False)