---
# Jenkins Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins

---
# ClusterRole for Jenkins
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins
  labels:
    app: jenkins
rules:
# Pod 관련 권한 (동적 에이전트 생성용)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "get"]

# ConfigMap, Secret 권한
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Service, Endpoints 권한  
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Deployment, ReplicaSet 권한 (배포용)
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Deployment 하위 리소스 권한 (rollout, scale 등)
- apiGroups: ["apps"]
  resources: ["deployments/status", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]

# Job 권한 (Kaniko 빌드용)
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Job 하위 리소스 권한 (status 확인용)
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get", "list", "watch"]

# Namespace 권한 (생성 권한 추가)
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# Events 조회 권한
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

# Node 조회 권한
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# PersistentVolume, PersistentVolumeClaim 권한
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# StorageClass 권한 (PVC 생성시 참조)
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

# Ingress 권한
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# IngressClass 권한 (Ingress 생성시 참조)
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
  labels:
    app: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins

---
# Additional Role for Jenkins namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins-namespace-admin
  labels:
    app: jenkins
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
# RoleBinding for Jenkins namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-namespace-admin
  namespace: jenkins
  labels:
    app: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-namespace-admin
  apiGroup: rbac.authorization.k8s.io 